MusicOnDemand/MusicOnDemand/Controllers/IzvodjacController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MusicOnDemand.Models;

namespace MusicOnDemand.Controllers
{
    public class IzvodjacController : Controller
    {
        private MusicDB_Entities db = new MusicDB_Entities();

        // GET: /Izvodjac/
        public async Task<ActionResult> Index(string search = "")
        {
            if (search == "") {
                var izvođač = db.izvođač.Include(i => i.država);
                return View(await izvođač.ToListAsync());
          
            }
            var izvođačFilter = db.izvođač.Include(i => i.država).Where( k => k.nazivIzvođač.Trim().Contains(search.Trim()));
            return View(await izvođačFilter.ToListAsync());
        }

        // GET: /Izvodjac/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            izvođač izvođač = await db.izvođač.Include("album").FirstAsync(t => t.izvođačID == id);
            if (izvođač == null)
            {
                return HttpNotFound();
            }
            return View(izvođač);
        }

        // GET: /Izvodjac/Create
        public ActionResult Create()
        {
            ViewBag.državaID = new SelectList(db.država, "državaID", "nazivDržave");
            return View();
        }

        // POST: /Izvodjac/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="izvođačID,nazivIzvođač,državaID")] izvođač izvođač)
        {
            if (ModelState.IsValid)
            {
                db.izvođač.Add(izvođač);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.državaID = new SelectList(db.država, "državaID", "nazivDržave", izvođač.državaID);
            return View(izvođač);
        }

        // GET: /Izvodjac/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            izvođač izvođač = await db.izvođač.FindAsync(id);
            if (izvođač == null)
            {
                return HttpNotFound();
            }
            ViewBag.državaID = new SelectList(db.država, "državaID", "nazivDržave", izvođač.državaID);
            return View(izvođač);
        }

        // POST: /Izvodjac/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="izvođačID,nazivIzvođač,državaID")] izvođač izvođač)
        {
            if (ModelState.IsValid)
            {
                db.Entry(izvođač).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.državaID = new SelectList(db.država, "državaID", "nazivDržave", izvođač.državaID);
            return View(izvođač);
        }

        // GET: /Izvodjac/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            izvođač izvođač = await db.izvođač.FindAsync(id);
            if (izvođač == null)
            {
                return HttpNotFound();
            }
            return View(izvođač);
        }

        // POST: /Izvodjac/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            izvođač izvođač = await db.izvođač.FindAsync(id);
            db.izvođač.Remove(izvođač);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MusicOnDemand/MusicOnDemand/Views/Izvodjac/Create.cshtml
@model MusicOnDemand.Models.izvođač

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>izvođač</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.izvođačID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.izvođačID)
                @Html.ValidationMessageFor(model => model.izvođačID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nazivIzvođač, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazivIzvođač)
                @Html.ValidationMessageFor(model => model.nazivIzvođač)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.državaID, "državaID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("državaID", String.Empty)
                @Html.ValidationMessageFor(model => model.državaID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicOnDemand/MusicOnDemand/Views/Izvodjac/Delete.cshtml
@model MusicOnDemand.Models.izvođač

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>izvođač</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazivIzvođač)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazivIzvođač)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.država.nazivDržave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.država.nazivDržave)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MusicOnDemand/MusicOnDemand/Views/Izvodjac/Details.cshtml
@model MusicOnDemand.Models.izvođač

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>izvođač</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazivIzvođač)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazivIzvođač)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.država.nazivDržave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.država.nazivDržave)
        </dd>

        <dt>
           
            @Html.DisplayNameFor(model => model.album)
        </dt>

        <dd>
            @foreach( MusicOnDemand.Models.album item in Model.album){
                <a href='@("/Album/Details/"+ item.albumID)'>@item.nazivAlbuma</a>
            }
          
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.izvođačID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MusicOnDemand/MusicOnDemand/Views/Izvodjac/Edit.cshtml
@model MusicOnDemand.Models.izvođač

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>izvođač</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.izvođačID)

        <div class="form-group">
            @Html.LabelFor(model => model.nazivIzvođač, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazivIzvođač)
                @Html.ValidationMessageFor(model => model.nazivIzvođač)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.državaID, "državaID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("državaID", String.Empty)
                @Html.ValidationMessageFor(model => model.državaID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicOnDemand/MusicOnDemand/Views/Izvodjac/Index.cshtml
@model IEnumerable<MusicOnDemand.Models.izvođač>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "Izvodjac", FormMethod.Get))
{
    @Html.TextBox("search", "", new { @id = "search-textbox" })

    <input type="submit" class=" btn btn-primary btn-large" />
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nazivIzvođač)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.država.nazivDržave)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nazivIzvođač)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.država.nazivDržave)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.izvođačID }) |
            @Html.ActionLink("Details", "Details", new { id=item.izvođačID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.izvođačID })
        </td>
    </tr>
}

</table>